const KEY="unboxlove_products";let editing=-1;
const defaults=[{name:"Love Resin Keychain",price:299,cat:"Keychains",desc:"A cute personalised resin keychain.",image:""},{name:"Mini Gift Hamper",price:799,cat:"Gift Hampers",desc:"A sweet little hamper for someone special.",image:""},{name:"Resin Name Art",price:699,cat:"Resin Art",desc:"Handmade resin art with a personalised touch.",image:""},{name:"Ribbon Love Bouquet",price:599,cat:"Ribbon Bouquets",desc:"A forever bouquet made with beautiful ribbons.",image:""}];
function get(){let p=JSON.parse(localStorage.getItem(KEY));if(!p){p=defaults;save(p)}return p}function save(p){localStorage.setItem(KEY,JSON.stringify(p))}
function login(){let u=document.querySelector("#user").value,p=document.querySelector("#pass").value;if(u==="admin"&&p==="unboxlove"){sessionStorage.admin="1";show()}else document.querySelector("#loginMsg").textContent="Wrong username or password."}
function logout(){sessionStorage.removeItem("admin");location.reload()}function show(){document.querySelector("#loginBox").classList.add("hidden");document.querySelector("#dashboard").classList.remove("hidden");render()}
function esc(s){return String(s??"").replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;")}
function render(){let p=get();document.querySelector("#adminGrid").innerHTML=p.map((x,i)=>`<div class="admin-card"><div class="pic" ${x.image?`style="background-image:url('${x.image.replaceAll("'","%27")}')"`:""}>${x.image?"":"🎁"}</div><h3>${esc(x.name)}</h3><small>${esc(x.cat)} · ₹${Number(x.price).toLocaleString("en-IN")}</small><p>${esc(x.desc)}</p><div class="actions"><button class="edit" onclick="edit(${i})">Edit</button><button class="delete" onclick="del(${i})">Delete</button></div></div>`).join("")}
document.querySelector("#productForm").addEventListener("submit",e=>{e.preventDefault();let p=get(),item={name:pname.value,price:Number(pprice.value),cat:pcat.value,desc:pdesc.value,image:pimage.value};if(editing<0)p.push(item);else p[editing]=item;save(p);resetForm();render()});
function edit(i){let x=get()[i];editing=i;pname.value=x.name;pprice.value=x.price;pcat.value=x.cat;pdesc.value=x.desc||"";pimage.value=x.image||"";document.querySelector("#formTitle").textContent="Edit Product";scrollTo({top:0,behavior:"smooth"})}
function del(i){if(confirm("Delete this product?")){let p=get();p.splice(i,1);save(p);render()}}
function resetForm(){editing=-1;document.querySelector("#productForm").reset();document.querySelector("#formTitle").textContent="Add Product"}
if(sessionStorage.admin==="1")show();