const defaults=[{id:1,name:'Rose Ribbon Bouquet',cat:'Ribbon Bouquet',price:899,emoji:'💐',desc:'Elegant handmade ribbon flowers.'},{id:2,name:'Forever Love Hamper',cat:'Gift Hamper',price:1299,emoji:'🎁',desc:'A beautiful curated surprise hamper.'},{id:3,name:'Resin Heart Keepsake',cat:'Resin Art',price:699,emoji:'💖',desc:'A glossy heart made to keep forever.'},{id:4,name:'Handmade Memory Box',cat:'Handmade Gifts',price:599,emoji:'🧸',desc:'A sweet little personalised gift.'},{id:5,name:'Mini Ribbon Bouquet',cat:'Ribbon Bouquet',price:499,emoji:'🌷',desc:'A cute bouquet for a little surprise.'},{id:6,name:'Resin Initial Keychain',cat:'Resin Art',price:349,emoji:'✨',desc:'A pretty resin keepsake for your keys.'},{id:7,name:'Birthday Gift Hamper',cat:'Gift Hamper',price:1099,emoji:'🎀',desc:'Thoughtful goodies packed together.'},{id:8,name:'Love Notes Gift Set',cat:'Handmade Gifts',price:449,emoji:'💌',desc:'Tiny handmade notes with big feelings.'}];let products=JSON.parse(localStorage.getItem('ul_products'))||defaults,cart=JSON.parse(localStorage.getItem('ul_cart'))||[],filter='All';const save=()=>{localStorage.setItem('ul_products',JSON.stringify(products));localStorage.setItem('ul_cart',JSON.stringify(cart))};function render(){let cats=['All','Ribbon Bouquet','Handmade Gifts','Resin Art','Gift Hamper'];document.getElementById('cats').innerHTML=cats.map(c=>`<button class="cat ${filter===c?'active':''}" onclick="setFilter('${c}')">${c}</button>`).join('');let list=filter==='All'?products:products.filter(p=>p.cat===filter);document.getElementById('products').innerHTML=list.map(p=>`<article class="card"><div class="visual">${p.emoji||'🎁'}</div><div class="info"><h3>${p.name}</h3><p>${p.desc||''}</p><span class="price">₹${p.price}</span><button class="add" onclick="add(${p.id})">Add +</button></div></article>`).join('');document.getElementById('cartCount').textContent=cart.reduce((a,x)=>a+x.qty,0)}function setFilter(x){filter=x;render()}function add(id){let x=cart.find(i=>i.id===id);x?x.qty++:cart.push({id,qty:1});save();render();openCart()}function openCart(){document.getElementById('modal').classList.remove('hidden');renderCart()}function closeCart(){document.getElementById('modal').classList.add('hidden')}function renderCart(){let total=0;document.getElementById('items').innerHTML=cart.length?cart.map(i=>{let p=products.find(x=>x.id===i.id),s=p.price*i.qty;total+=s;return `<div class="row"><span>${p.name} × ${i.qty}</span><b>₹${s}</b><button onclick="removeItem(${i.id})">×</button></div>`}).join(''):'<p>Your bag is empty.</p>';document.getElementById('total').textContent=total}function removeItem(id){cart=cart.filter(x=>x.id!==id);save();render();renderCart()}function orderWhatsApp(){
 if(!cart.length)return alert('Your bag is empty');
 const name=document.getElementById('custName').value.trim();
 const phoneCustomer=document.getElementById('custPhone').value.trim();
 const address=document.getElementById('custAddress').value.trim();
 const city=document.getElementById('custCity').value.trim();
 const pincode=document.getElementById('custPincode').value.trim();
 if(!name||!phoneCustomer||!address||!city||!pincode)return alert('Please fill all delivery details ❤️');
 if(!/^\\d{10}$/.test(phoneCustomer.replace(/\\D/g,'')))return alert('Please enter a valid 10-digit mobile number');
 if(!/^\\d{6}$/.test(pincode))return alert('Please enter a valid 6-digit pincode');
 let phone=localStorage.getItem('ul_whatsapp')||'919999999999',total=0;
 let lines=cart.map(i=>{let p=products.find(x=>x.id===i.id),s=p.price*i.qty;total+=s;return `${p.name} x ${i.qty} = ₹${s}`}).join('\\n');
 let msg=`Hi Unbox Love!%0A%0A*New Order*%0A${encodeURIComponent(lines)}%0A%0A*Customer Details*%0AName: ${encodeURIComponent(name)}%0AMobile: ${encodeURIComponent(phoneCustomer)}%0AAddress: ${encodeURIComponent(address)}%0ACity: ${encodeURIComponent(city)}%0APincode: ${encodeURIComponent(pincode)}%0A%0ATotal: ₹${total}%0A%0APlease send me the WhatsApp payment QR.`;
 location.href=`https://wa.me/${phone}?text=${msg}`;
}
document.getElementById('cartBtn').onclick=openCart;render();